_name: "Make indexes Config (default)"

input_path: "./data/features/hindi/mel"
output_path: "./data/indexes/hindi"

indexer_name: hindi

split_all:
  train: 80
  dev: 29

split_train:
  train: 200
  dev: 20
